language: generic

env:
  - GHCVER=7.6.3  CABALVER=1.22
  - GHCVER=7.8.4  CABALVER=1.22
  - GHCVER=7.10.1 CABALVER=1.22
  - GHCVER=8.0.1  CABALVER=1.24

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - sudo apt-get install cabal-install-$CABALVER
  - export PATH=/opt/cabal/$CABALVER/bin:$PATH
  - ghc --version
  - cabal --version
  - cabal update

script:
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests --ghc-options='-Werror' && cabal build && cabal test
  - cabal install --ghc-options='-Werror'
