name: Ci

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request: {}

jobs:
  stack-based:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack_yaml:
          - stack-ghc-8.0.yaml
          - stack-ghc-8.2.yaml
          - stack-ghc-8.4.yaml
          - stack-ghc-8.6.yaml
          - stack-ghc-8.8.yaml
          - stack-ghc-8.10.yaml
          - stack-ghc-9.0.yaml
          - stack-ghc-9.2.yaml
          - stack-text-2.0.yaml
    steps:
      - name: Set STACK_YAML
        run: echo STACK_YAML=${{ matrix.stack_yaml }} >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: 1-${{ matrix.stack_yaml }}

      - name: Setup
        run: stack setup

      - name: Info
        run: |
          stack --version
          stack ghc -- --version
          echo STACK_YAML=$STACK_YAML

      - name: Install Dependencies
        run: stack build --test --only-dependencies --haddock-deps

      - name: Test
        run: stack test --ghc-options=-Wall

      - name: Docs
        run: stack haddock
